# Generated by Django 3.1.6 on 2021-03-02 11:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('email_id', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('days_to_do', models.IntegerField()),
                ('deadline', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('is_complete', models.BooleanField(default=False, null=True)),
                ('completed_on_time', models.BooleanField(default=False, null=True)),
                ('priority', models.CharField(choices=[('highest', 'highest'), ('primary', 'primary'), ('secondary', 'secondary'), ('tertiary', 'tertiary')], max_length=32)),
                ('user_name_fill', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.beneficiare')),
            ],
        ),
    ]
