# Generated by Django 3.1.6 on 2021-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210302_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='user_name_fill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
