# Generated by Django 3.1.6 on 2021-03-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210302_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user_name_fill',
        ),
    ]
